// The built stylesheets are the source of truth for every story in here.
// They are generated by `npm run build-tokens` and are gitignored, so
// Storybook always runs the build first (see the npm scripts).
import "../build/css/tokens.css";
import "../build/css/typography.web.css";
import "../build/css/typography.mobile.css";
import "../build/css/typography.back-office.css";
// Inter, vendored locally so the type specimens render in the real face
// rather than the browser's default serif. `--font-family-sans` is the bare
// string "Inter" with no fallback stack, so the font has to actually be here.
import "@fontsource/inter/400.css";
import "@fontsource/inter/500.css";
import "@fontsource/inter/600.css";
import "./gallery.css";

/** @type {import('@storybook/html-vite').Preview} */
const preview = {
  parameters: {
    layout: "fullscreen",
    controls: { expanded: true },
    options: {
      storySort: {
        order: [
          "Overview",
          "Core Palette",
          "Semantic Colour",
          "Typography",
          "Spacing",
          "Radius & Border",
          "Elevation"
        ]
      }
    }
  }
};

export default preview;
